package com.bookSphere.bookSphere;
import com.bookSphere.bookSphere.models.*;
import com.bookSphere.bookSphere.repositories.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;

@SpringBootApplication
public class BookSphereApplication {
	public static void main(String[] args) {
		SpringApplication.run(BookSphereApplication.class, args);
	}
	@Autowired
	PasswordEncoder passwordEncoder;
	@Bean
	public CommandLineRunner initData(ClientRepository clientRepository, BookRepository bookRepository, FeaturedAuthorRepository featuredAuthorRepository, EventsRepository eventsRepository, UserMessageRepository userMessageRepository, BuyOrderRepository buyOrderRepository) {
		return args -> {
			//EVENTS

			Events event1 = new Events("Winter Reading Festival","https://malba.s3.sa-east-1.amazonaws.com/wp-content/uploads/2023/06/2023-07-06-172554-750x578.jpg","At each change of season, Book Sphere organizes a new edition of the Reading Festival, an opportunity to spend time in the company of readers and books. An invitation to share with friends and disconnect from technology. This winter it will be dedicated especially to comics and graphic novels with a selection of more than 60 titles to see and share. Participating in this selection are titles from Cápsula editions, Comiks Debris, Editorial Común, Historieteca, Hotel de las Ideas, Libera la beast, Libros del Zorzal, Loco Rabia editions, Merci, Kill the Messenger, Pictus and Penguin Random House. In addition, the Book Sphere store will be open with a selection of national and international comic book titles and books and catalogues.", 25, LocalTime.of(15, 30), LocalDate.of(2023, 8, 5),false, EventRoom.ROOMA);
			Events event2 = new Events("Emerging poetry", "https://www.ncwlibraries.org/wp-content/uploads/poetry-month_blog-1080x621.jpg", "It is a space whose purpose is to give visibility to poets from our country regardless of their age: young people, adults and older adults. who, although they carry out their work outside the main editorial circuits, honor the craft of writing with a Valuable poetic work that deserves to be disseminated and shared. Some of these authors, distinguished with prizes in their localities, have published their works through independent editions, in poetry blogs and participate in literary workshops, popular libraries, etc.", 30, LocalTime.of(9, 15), LocalDate.of(2023, 8, 20),false,EventRoom.ROOMB);
			Events event3 = new Events("Comics Workshop", "https://www.cronista.com/files/image/479/479001/6328bd73bd09a.jpg", "Mythical comics of Argentina and construction of characters Our country has a fabulous comic strip tradition, very popular among its readers. We will focus on the construction of its main characters and, using them as triggers, we will put together a character design bible to invent a new one, ready to live its own adventures. We are going to visit Patoruzú, by Dante Quinterno, Pelopincho and Cachirula, by Fola, Pi-Pío, by Manuel García Ferré, El Eternauta, by Oesterheld and Solano López, Sonoman, by Oswald, Nippur by Lagash, by Robin Wood and Lucho Olivera and Mafalda, from Quino." ,30, LocalTime.of(14, 45),LocalDate.of(2023, 9, 30),false,EventRoom.ROOMA);
			Events event4 = new Events("Remembering Maria Elena Walsh", "https://fhaycs-uader.edu.ar/images/2023/mari%CC%81a-elena-walsh.jpeg", "Symphonic Karaoke: Join us in a unique experience where music, poetry and fun come together to pay homage to the great figure of Argentine culture. In this exciting karaoke concert, you will be able to enjoy the most emblematic songs by María Elena Walsh performed by you and your family. Yes, you will be the star on the stage! Accompanied by the talented local Camerata Académica and guest musicians, you'll create a magical atmosphere as you sing the endearing melodies of this iconic singer-songwriter and writer.", 45, LocalTime.of(17, 20), LocalDate.of(2023, 10, 8), false,EventRoom.ROOMB);
			Events event5 = new Events("40 years, 40 works", "https://www.lavoz.com.ar/resizer/OM7U5FRdwbSkLN5qhRL5PYKvD1E=/980x640/smart/filters:quality(75):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/CMXBCUOEJVC7VET62K54H3QBVI.jpg", "Celebrate with us an event that explores the link between theater, music, cinema, and thought with democracy. We will revive emblematic works, reflect on the present state of democracy, and engage in debates about its future. Join this enriching experience that combines historical reenactments and thoughtful exercises to strengthen democratic values. Participate and let's celebrate art, culture, and freedom of expression together!", 40, LocalTime.of(10, 15), LocalDate.of(2023, 10, 20),false,EventRoom.ROOMA );
			Events event6 = new Events("Oral storytelling workshop" , "https://cdn.discordapp.com/attachments/1118745167109832724/1134201694088089670/95fcf9d1cd9df8a76d662d40af97f6a2.jpg" , "It is a workshop of oral interpretation and reading aloud. Our team of instructors will guide you in the process of overcoming any shyness or nervousness when speaking in public, providing you with tools to express yourself with confidence and security. Through breathing exercises, vocalization and body expression. Throughout the meetings, we will discover and deepen our skills to narrate and for this we will train our body expression and some dimensions of the transfer of the text to orality. Join us and discover the power of your voice!", 55,LocalTime.of(16, 30), LocalDate.of(2023, 11, 24), false,EventRoom.ROOMB );

			eventsRepository.saveAll(Arrays.asList(event1,event2,event3,event4,event5,event6));
			//CLIENTS:

			Client client = new Client("Marco", "Miquel", "miquel.marco@outlook.com", passwordEncoder.encode("123"),true);
			Client client1=new Client("Santiago","Gamarra","santi@gmail.com",passwordEncoder.encode("123"),true);
			Client admin=new Client("admin","admin","admin@admin.com", passwordEncoder.encode("123"),true);
			Client client2= new Client("Natalia", "Carrasco", "nati@gmail.com", passwordEncoder.encode("123123123123"),false );
			clientRepository.save(client);
			clientRepository.save(client1);
			clientRepository.save(admin);
			clientRepository.save(client2);

			//BOOKS:

			Book book = new Book("9780525559757", "Bunny", "Mona Awad", "Fantasy", "As Samantha plunges deeper and deeper into the Bunnies' sinister yet saccharine world, beginning to take part in the ritualistic off-campus Workshop where they conjure their monstrous creations, the edges of reality begin to blur.", "https://images.cdn3.buscalibre.com/fit-in/360x360/16/cb/16cb7e50cad538cb1b6ee2e2d980e55e.jpg", 10, 15.36, 10,false);
			Book book1 = new Book("9780142437247", "Moby Dick", "Herman Melville", "Fantasy", "Written with wonderfully redemptive humor, Moby-Dick is a profound and timeless inquiry into character, faith, and the nature of perception.", "https://images.cdn2.buscalibre.com/fit-in/360x360/26/67/26673e9c4286d6be1b36a71d083a621a.jpg", 10, 13.12,0,false);
			Book book2 = new Book("9781478948421", "Master of the Game", "Sidney Sheldon", "Fantasy", "She is the symbol of success, the beautiful woman who parlayed her inheritance into an international conglomerate. Winner of a unique position among the wealthy and world-renowned.", "https://images.cdn3.buscalibre.com/fit-in/360x360/ed/9f/ed9f8c3874a3e396c9e9fb53df245187.jpg", 10, 24.66,15,false);
			Book book3 = new Book("9781101885994", "The Winter of the Witch", "Katherine Arden", "Fantasy", "A wicked demon returns, determined to spread chaos. Caught at the center of the conflict is Vasya, who finds the fate of two worlds resting on her shoulders.", "https://images.cdn2.buscalibre.com/fit-in/360x360/2b/59/2b59722838d31562060bfaec2067bd5d.jpg", 10, 22.40,0,false);
			Book book4 = new Book("9781501161933", "The Seven Husbands of Evelyn Hugo", "Taylor Jenkins", "Fantasy", "Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.", "https://images.cdn1.buscalibre.com/fit-in/360x360/13/11/1311105ce84c560dfceba479e7f12cc4.jpg", 10, 13.65,0,false);
			Book book5 = new Book("9781484707234", "Percy Jackson and the Olympians 5 Book", "Rick Riordan", "Fantasy", "All five books in the blockbuster Percy Jackson and the Olympians series, in paperback, collected in a boxed set fit for demigods, complete with a bonus poster!", "https://images.cdn1.buscalibre.com/fit-in/360x360/76/17/761780140b8bb068b2d364df4a0863a9.jpg", 10, 23.27,0,false);
			Book book6 = new Book("9781668021910", "Heart Bones", "Colleen Hoover", "Fantasy", "After a childhood filled with poverty and neglect, Beyah Grim finally has her hard-earned ticket out of Kentucky with a full ride to Penn State.", "https://images-ext-1.discordapp.net/external/zYKeH2VUwycN3fWu0yrq-wvMdUFYuw1_pgnIYxAYlXk/https/images.cdn2.buscalibre.com/fit-in/360x360/bd/82/bd82df1fc93539ad1af186e06a1296c2.jpg?width=288&height=450", 10, 14.86,20,false);
			Book book7 = new Book("9781984806758", "People we Meet on Vacation", "Emily Henry", "Fantasy", "She's a wild child; he wears khakis. She has insatiable wanderlust; he prefers to stay home with a book.", "https://images.cdn2.buscalibre.com/fit-in/360x360/7d/cd/7dcdedc9d397d92395c491eb19e521b1.jpg", 10, 13.46,0,false);
			Book book8 = new Book("9780399555817", "Starsight", "Brandon Sanderson", "Fantasy", "All her life, Spensa's dreamed of becoming a pilot and proving herself a hero like her father. She made it to the sky, but the truths she learned there were crushing.", "https://images.cdn1.buscalibre.com/fit-in/360x360/a4/18/a418a57d6902a0f0231063d718755bde.jpg", 10, 17.59,0,false);
			Book book9 = new Book("9780765360038", "Warbreaker", "Brandon Sanderson", "Fantasy", "In the world of Warbreaker, each person is born endowed with the power of one Breath--which can be sold and collected by others, then used to Awaken objects and even corpses to do their bidding.", "https://images.cdn1.buscalibre.com/fit-in/360x360/c9/d4/c9d4b1218092596959a2c22aaae133ea.jpg", 10, 10.61,0,false);
			Book book10 = new Book("9780385743617", "Calamity", "Brandon Sanderson", "Fantasy", "When Calamity lit up the sky, the Epics were born. David's fate has been tied to their villainy ever since that historic night. Steelheart killed his father. Firefight stole his heart.", "https://images.cdn2.buscalibre.com/fit-in/360x360/0e/db/0edb4728fd1944d1dd39fcb68d2c4b52.jpg", 10, 9.59,0,false);

			//horror

			Book book11 = new Book("9780307743657", "The Shining", "Stephen King", "Horror", "Before Doctor Sleep, there was The Shining, a classic of modern American horror from the undisputed master, Stephen King.", "https://images.cdn2.buscalibre.com/fit-in/360x360/e1/4e/e14ec719ab6bb40edc665ade65bad78e.jpg", 10, 9.99,0,false);
			Book book12 = new Book("9780345337665", "Interview With the Vampire", "Anne Rice", "Horror", "Hypnotic, shocking, and chillingly sensual, this is a novel of mesmerizing beauty and astonishing force--a story of danger and flight, of love and loss, of suspense and resolution.", "https://images.cdn1.buscalibre.com/fit-in/360x360/c5/d2/c5d28268d3b115360867a3a55458b6b6.jpg", 10, 7.19,10,false);
			Book book13 = new Book("9781501182099", "It: A Novel", "Stephen King", "Horror", "Welcome to Derry, Maine. It's a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real.", "https://images.cdn2.buscalibre.com/fit-in/360x360/2a/88/2a88c91d343e3eb9a5110d76b03a85fe.jpg", 10, 23.63, 0,false);
			Book book14 = new Book("9780345514257", "House of Reckoning", "John Saul", "Horror", "After the untimely death of her mother and the arrest of her father for killing a man in barroom brawl, fourteen-year-old Sarah Crane is forced to grow up fast.", "https://images.cdn3.buscalibre.com/fit-in/360x360/c5/f3/c5f31344a8a1cdc8042b329ddb4eeb66.jpg", 10, 6.39,0,false);
			Book book15 = new Book("9781728220239", "From Below", "Darcy Coates", "Horror", "Hundreds of feet beneath the ocean's surface, a graveyard waits...Years ago, the SS Arcadia vanished without a trace during a routine voyage.", "https://images.cdn3.buscalibre.com/fit-in/360x360/b9/ae/b9aeba3cbcdfebbd190decc7b82a1c52.jpg", 10, 9.57,0,false);
			Book book16 = new Book("9781587678011", "Gwendy, Final Task", "Stephen King", "Horror", "When Gwendy Peterson was twelve, a mysterious stranger named Richard Farris gave her a mysterious box for safekeeping. It offered treats and vintage coins, but it was dangerous.", "https://images.cdn2.buscalibre.com/fit-in/360x360/27/2e/272e5d17ef49992bc5b46592f74c9a1a.jpg", 10, 22.40,0,false);
			Book book17 = new Book("9780440242864", "Hannibal Rising", "Thomas Harris", "Horror", "He is one of the most haunting characters in all of literature. At last the evolution of his evil is revealed. Hannibal Lecter emerges from the nightmare of the Eastern Front, a boy in the snow, mute, with a chain around his neck.", "https://images.cdn3.buscalibre.com/fit-in/360x360/5e/d5/5ed5c62b738d212c94bb57034f4a0452.jpg", 10, 7.19,5,false);
			Book book18 = new Book("9780692799642", "The Secret of Ventriloquism", "Jon Padgett", "Horror", "With themes reminiscent of Shirley Jackson, Thomas Ligotti, and Bruno Schulz, but with a strikingly unique vision, Jon Padgett's The Secret of Ventriloquism heralds the arrival of a significant new literary talent.", "https://images.cdn2.buscalibre.com/fit-in/360x360/b1/83/b183372998ccba4dbe21f29b22957a4c.jpg", 10, 10.39,0,false);
			Book book19 = new Book("9780345350800", "Bloodcurdling Tales of Horror and the Macabre", "H. P. Lovecraft", "Horror", "This is the collection that true fans of horror fiction must have: sixteen of H.P. Lovecraft's most horrifying visions, including: The Call of Cthulu.", "https://images.cdn1.buscalibre.com/fit-in/360x360/29/76/29763505196b96524f84e27b1620943c.jpg", 10, 14.40, 0,false);
			Book book20 = new Book("9781591434313", "Revelations From the Source", "Bárbara Hand Clow", "Horror", "The characters, as well as readers, experience moving out of fear-based consciousness to the higher dimensions.", "https://images.cdn3.buscalibre.com/fit-in/360x360/ce/b3/ceb3402706217ed30df4ace8c0cfc62c.jpg", 10, 14.40,0,false);

			//Self care

			Book book21 = new Book("9780345497796", "Healthy Sleep Habits, Happy Twins", "Marc Weissbluth", "Selfcare", "As parents of twins and multiples know, double the fun can be double the sleep deprivation.", "https://images.cdn2.buscalibre.com/fit-in/360x360/25/37/253768deb67a5baf8f412c94b78e6a92.jpg", 10, 13.60,0,false);
			Book book22 = new Book("9780964838345", "Codependence the Dance of Wounded Souls", "Robert Burney", "Selfcare", "Metaphysical Truth, and Native American Spirituality with quantum physics and molecular biology in sharing a perspective of the human experience that can lead to a life-changing Spiritual Awakening.", "https://images.cdn3.buscalibre.com/fit-in/360x360/ad/de/addee37c7f101c34d7d0697d6e75f4a7.jpg", 10, 14.36,10,false);
			Book book23 = new Book("9780062905154", "Wabi Sabi", "Beth Kempton", "Selfcare", "The definitive guide that teaches you how to use the Japanese concept of wabi sabi to reshape every area of your life and find happiness right where you are.", "https://images.cdn2.buscalibre.com/fit-in/360x360/75/f9/75f9d9affadb81e3cb35437f7b7315fa.jpg", 10, 17.59,0,false);
			Book book24 = new Book("9781585429134", "Attached", "Amir Levine", "Selfcare", "Discover how an understanding of adult attachment--the most advanced relationship science in existence today--can help us find and sustain love.", "https://images.cdn2.buscalibre.com/fit-in/360x360/ad/3d/ad3da45bae11be34084e140232abbddb.jpg", 10, 13.65,0,false);
			Book book25 = new Book("9780062203571", "The Book of Forgiving", "Desmond Tutu", "Selfcare", "Archbishop Desmond Tutu, Nobel Peace Prize winner, Chair of The Elders, and Chair of South Africa's Truth and Reconciliation Commission, along with his daughter, the Reverend Mpho Tutu, offer a manual on the art of forgiveness--helping us to realize that we are all capable of healing and transformation.", "https://images.cdn3.buscalibre.com/fit-in/360x360/36/96/3696fbe545df70e94d09b47b8ea09c85.jpg", 10, 13.59,0,false);
			Book book26 = new Book("9781982183066", "8 Rules of Love", "Jay Shetty", "Selfcare", "Nobody sits us down and teaches us how to love. So we're often thrown into relationships with nothing but romance movies and pop culture to help us muddle through.", "https://images.cdn1.buscalibre.com/fit-in/360x360/08/27/08273a81b1aa6f8e9604ee6ac871a38e.jpg", 10, 21.43,5,false);
			Book book27 = new Book("9781622038329", "Way of the Superior Man", "David Deida", "Selfcare", "Though much has changed in society since the first publication of The Way of the Superior Man, men of all ages still tussle with the challenges of women, work, and sexual desire.", "https://images.cdn2.buscalibre.com/fit-in/360x360/74/6e/746e6fb17fdefcd31ff3c3ae1df26e3d.jpg", 10, 17.74,0,false);
			Book book28 = new Book("9781878424310", "The Four Agreements", "Don Miguel Ruiz", "Selfcare", "In The Four Agreements, bestselling author don Miguel Ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering.", "https://images.cdn2.buscalibre.com/fit-in/360x360/4d/ac/4dacc50778d7ea7d2ad0426cd4cbdcb5.jpg", 10, 11.54,0,false);
			Book book29 = new Book("9781532814655", "Reality Transurfing", "Vadim Zeland", "Selfcare", "Transurfing is a powerful tool for managing reality. Apply it and life will begin to change according to YOUR order. When you use Transurfing goals are not reached, so much as realised for the most part of themselves.", "https://images.cdn2.buscalibre.com/fit-in/360x360/09/1b/091b44fa175ea15e728c46f71008eb3b.jpg", 10, 57.56,0,false);
			Book book30 = new Book("9780593189689", "Burn After Writing", "Sharon Jones", "Selfcare", "Burn After Writing allows you to spend less time scrolling and more time self-reflecting. Through incisive questions and thought experiments, this journal helps you learn new things while letting others go.", "https://images.cdn2.buscalibre.com/fit-in/360x360/6a/bb/6abb0b494ed8ae93b0b34c53fd70beb1.jpg", 10, 11.20,0,false);


			//Romantic

			Book book31 = new Book("9781949364262", "Sinner", "Sierra Simone", "Romantic", "From USA Today and Wall Street Journal bestselling author Sierra Simone comes her steamy, TikTok-famous Priest series, in which sinners and saints alike test the bonds of religion, love, and lust.", "https://images.cdn3.buscalibre.com/fit-in/360x360/19/00/1900c2d381d0c864d2b727329615fabe.jpg", 10, 14.94,5,false);
			Book book32 = new Book("9781478948353", "Dear John", "Nicholas Sparks", "Romantic", "When a rebel serving in the Army meets the girl of his dreams, he must face an impossible choice as a national tragedy forces them apart in this powerful New York Times bestseller.", "https://images.cdn3.buscalibre.com/fit-in/360x360/2c/46/2c46e13b3bdbc716e9dd565101f22b17.jpg", 10, 6.39,0,false);
			Book book33 = new Book("9781538724736", "Verity", "Colleen Hoover", "Romantic", "Lowen Ashleigh is a struggling writer on the brink of financial ruin when she accepts the job offer of a lifetime.", "https://images.cdn2.buscalibre.com/fit-in/360x360/5b/e1/5be1e92803bff461b78d39e88fb01d22.jpg", 10, 14.06,0,false);
			Book book34 = new Book("9781335458520", "The Long Game", "Rachel Reid", "Romantic", "Ten years.That's how long Shane Hollander and Ilya Rozanov have been seeing each other. How long they've been keeping their relationship a secret.", "https://images.cdn3.buscalibre.com/fit-in/360x360/1e/1c/1e1c4eb414eb3966a45e8150e08cf2e0.jpg", 10, 7.19,0,false);
			Book book35 = new Book("9781792803215", "Twisted Emotions", "Cora Reilly", "Romantic", "Nino Falcone is genius and monster. As the right hand man and brother of the Capo of the Camorra, his lack of feelings is a blessing, not a curse - until his brother asks him to marry for the sake of the Camorra.", "https://images.cdn3.buscalibre.com/fit-in/360x360/88/5d/885dcb5627e5a64ea77d349dd50b2652.jpg", 10, 11.99,25,false);
			Book book36 = new Book("9781094607665", "One Percent of you", "Michelle Gross", "Romantic", "Make no mistakes about it. I know what I look like to others. Young, government-aided, pregnant mom. They see Lucy on my hip, and they see a mistake.", "https://images.cdn2.buscalibre.com/fit-in/360x360/09/eb/09eb20a5ebe2985a80dc7876bf8e9c73.jpg", 10, 11.19,0,false);
			Book book37 = new Book("9780593498279", "The two Lives of Lydia Bird", "Josie Silver", "Romantic", "A powerful and thrilling love story about the what-ifs that arise at life's crossroads, and what happens when one woman is given a miraculous chance to answer them", "https://images.cdn1.buscalibre.com/fit-in/360x360/ca/65/ca65fb8269fe15872f86fdbd94451f65.jpg", 10, 7.19,0,false);
			Book book38 = new Book("9781535424127", "Master of the Game", "Lr Potter", "Romantic", "He was her complex opposite. He was strong while she felt weak. He was confident while she felt insecure. He was aggressive and obviously went for what he wanted, while she was hesitant and felt restrained.", "https://images.cdn2.buscalibre.com/fit-in/360x360/49/bd/49bdb16b2483848a6d1a60cb28e33952.jpg", 10, 7.99,10,false);
			Book book39 = new Book("9781649370297", "The Brides of London", "Vanessa Riley", "Romantic", "Fans of Bridgerton will love these two Regency romances for the price of one, featuring two best friends, each determined to advertise for love.", "https://images.cdn1.buscalibre.com/fit-in/360x360/79/cc/79cc3435a76f45920390bac5bb731fd2.jpg", 10, 7.99,0,false);
			Book book40 = new Book("9781649370235", "Forever Starts Now", "Stefanie London", "Romantic", "What happens when two people who’ve given up on forever find it in each other…?Single men are as scarce in Forever Falls as a vegetarian at a barbecue.", "https://images.cdn2.buscalibre.com/fit-in/360x360/16/a5/16a5b352ae410b1218b31ddf2e2275f7.jpg", 10, 7.19,0,false);

			//kids

			Book book41 = new Book("9780375846649", "Penguins and Antarctica", "Mary Pope Osborne", "Kids", "Who won the race to the South Pole? What happens at a research station in Antarctica? Find out the answers to these questions and more as Jack and Annie track the facts.", "https://images.cdn3.buscalibre.com/fit-in/360x360/6a/a2/6aa2ea3fd61a6a31d941264c8e7abfdc.jpg", 10, 5.59,15,false);
			Book book42 = new Book("9780692848388", "What Should Danny do?", "Adir Levy", "Kids", "What Should Danny Do? is an innovative, interactive book that empowers kids with the understanding that their choices will shape their days, and ultimately their lives into what they will be.", "https://images.cdn2.buscalibre.com/fit-in/360x360/62/90/6290b48f86da55b7aad3d99c02e34ed1.jpg", 10, 17.59,0,false);
			Book book43 = new Book("9780385738101", "A Really Short History of Nearly Everything", "Bill Bryson", "Kids", "Explore the mysteries of the universe without ever leaving your home! Bill Bryson takes on the world of science and answers questions big and small, perfect for curious readers looking to learn outside of the classroom!", "https://images.cdn1.buscalibre.com/fit-in/360x360/91/6a/916a3170a6a96882e92f0d2c6f3bfcbb.jpg", 10, 17.59,20,false);
			Book book44 = new Book("9780763669003", "Mango, Abuela, and Me", "Meg Medina", "Kids", "A 2016 Pura Belpré Author Award Honor BookA 2016 Pura Belpré Illustrator Award Honor Book When a little girl's far-away grandmother comes to stay, love and patience transcend language in a tender story written by acclaimed author Meg Medina.", "https://image.cdn0.buscalibre.com/5b57944df4df73b60e8b4567.__RS360x360__.jpg", 10, 14.39,0,false);
			Book book45 = new Book("9781536203288", "My Sweet Orange Tree", "José Mauro De Vasconcelos", "Kids", "Fifty years after its first publication, the multimillion-copy international bestseller is available again in English, sharing the heartbreaking tale of a gifted, mischievous, direly misunderstood boy growing up in Rio de Janeiro.", "https://images.cdn3.buscalibre.com/fit-in/360x360/68/14/6814efa3b67ee7c21084bd6df537f587.jpg", 10, 14.39,0,false);
			Book book46 = new Book("9780590353427", "Harry Potter and the Sorcerer's Stone", "J. K. Rowling", "Kids", "Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility.", "https://images.cdn3.buscalibre.com/fit-in/360x360/db/85/db854a296085295e18d6450cf9d09a45.jpg", 10, 8.79,0,false);
			Book book47 = new Book("9781984896698", "Kikis Delivery Service", "Eiko Kadono", "Kids", "Read the modern classic about a young witch and her clever cat that started it all! Nostalgic fans of the Hiyao Miyazaki film, Kiki's Delivery Service and newcomers alike will love this exciting new translation of the beloved fantasy story. ", "https://images.cdn2.buscalibre.com/fit-in/360x360/df/a4/dfa4a66b48b0313d303893ddaaf2ecbc.jpg", 10, 8.99,25,false);
			Book book48 = new Book("9780679889113", "My Father's Dragon", "Ruth Stiles Gannett", "Kids", "Rediscover the classic fantasy trilogy beginning with Newbery Honor winner My Father's Dragon in this 50th anniversary edition that includes three timeless tales in one, with original illustrations!", "https://images.cdn3.buscalibre.com/fit-in/360x360/90/f5/90f569e99c2aa78fefb508a92edce68f.jpg", 10, 13.56,0,false);
			Book book49 = new Book("9780989200943", "The boy who put Cookies in a Shoe", "Sherry Ann Mullens", "Kids", "An easy reader for children about a young boy who is disappointed when he gets an old Danish wooden shoe for his birthday.", "https://images-ext-2.discordapp.net/external/90D3OhUdNJD9-4OuM_mGnH6bOIR1uEb6gJCmkg7dd70/https/images.cdn1.buscalibre.com/fit-in/360x360/20/1f/201f9ee1f97bdabbd2efff88ccc92b0a.jpg?width=450&height=450", 10, 9.23,0,false);
			Book book50 = new Book("9788494671593", "Alphabeti-Cool", "Rebecca Bielawski", "Kids", "A B C D E F G so many letters on the alphabet tree. H I J K L M N O P spell all the words for the things we see. Q R S T U V, W's a tricky one, then X Y and Z !", "https://images.cdn1.buscalibre.com/fit-in/360x360/88/24/88242a564ff7a26f54c415d2a66ab974.jpg", 10, 9.59,0,false);
			bookRepository.saveAll(Arrays.asList(
					book, book1, book2, book3, book4, book5, book6, book7, book8, book9,
					book10, book11, book12, book13, book14, book15, book16, book17, book18, book19,
					book20, book21, book22, book23, book24, book25, book26, book27, book28, book29,
					book30, book31, book32, book33, book34, book35, book36, book37, book38, book39,
					book40, book41, book42, book43, book44, book45, book46, book47, book48, book49, book50
			));


			//FEATURED AUTHORS

			FeaturedAuthor author1=new FeaturedAuthor("Gabriel","Garcia Marquez","Colombian","Magical realism, Literary Fiction","Gabriel García Márquez was an internationally renowned Colombian writer, celebrated for his unique style and mastery of magical realism. His most famous work is \"One Hundred Years of Solitude,\" a novel that has been acclaimed as one of the masterpieces of Spanish literature. Through his poetic prose and captivating plots, García Márquez delved into themes such as loneliness, love, and the history of Latin America.","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAk0Tgov3nLiagGWVGtPrncHdQ2KLxyXvKmnCwTJEm6lyP2aGI9mws7X1Of-4eNFvRKT4&usqp=CAU",false);
			FeaturedAuthor author2=new FeaturedAuthor("Haruki","Murakami","Japanese","Contemporary fiction, magical realism, surrealism.","Haruki Murakami is a Japanese writer known for his introspective and surrealistic narrative. His unique style has captured the imagination of readers worldwide. His works often explore themes of loneliness, identity, and the mysteries of everyday life, blending realistic and dreamlike elements. Among his most popular works are Norwegian Wood and 1Q84.","https://s3.abcstatics.com/abc/www/multimedia/cultura/2023/05/24/murakami2-Rx1ptgeOnqPB6QpPClNoRYM-758x531@abc.JPG",false);
			FeaturedAuthor author3=new FeaturedAuthor("Chimamanda","Ngozi Adichie","Nigerian","Contemporary fiction, feminist literature.","Adichie is known for her focus on social, feminist, and identity-related themes in her works. Her novels often address issues of gender, race, and politics, providing a profound and poignant perspective on the African experience and the African diaspora.","https://phantom-elmundo.unidadeditorial.es/c38ac26b3cae372bdd70a9bc6471f9f3/crop/0x86/2048x1451/resize/990/f/webp/assets/multimedia/imagenes/2021/04/14/16184064620408.jpg",false);
			FeaturedAuthor author4=new FeaturedAuthor("J.K","Rowling","United Kingdom","Fantasy literature, young adult fiction.","Joanne Rowling, known by her pseudonym J.K. Rowling, is a British author famous for the Harry Potter book series. Her ability to create a magical world and unforgettable characters has captivated readers of all ages. The Harry Potter books have become a cultural phenomenon and have inspired movies and a wide range of products related to the wizarding universe.","https://images-na.ssl-images-amazon.com/images/S/amzn-author-media-prod/8cigckin175jtpsk3gs361r4ss.jpg",false);
			FeaturedAuthor author5=new FeaturedAuthor("Tony","Morrison","United States","Literary fiction, African American literature.","Toni Morrison was distinguished for her unique literary style and her focus on the African American experience in the United States. Her works explore themes of race, identity, history, and collective memory, and are considered significant contributions to African American literature and literature as a whole.","https://media.newyorker.com/photos/5d49ab78039a7b00093153ee/master/w_1600%2Cc_limit/TNY-ReadingToniMorrison.jpg",false);

			featuredAuthorRepository.saveAll(Arrays.asList(author1,author2,author3,author4,author5));


			UserMessage message1=new UserMessage("Santiago Gamarra","santi@gmail.com","(555) 123-4567","I would like to inquire whether you have the book \"[Book Title 1]\" by [Author of Book 1] in stock. I have heard a lot about this author and I am keen on acquiring this particular work. If it is available, I would appreciate it if you could provide me with information regarding its price and whether it can be reserved.",LocalDate.now());
			userMessageRepository.save(message1);
			UserMessage message2=new UserMessage("Natalia Requena","natirm@gmail.com","(553) 123-2267","I have heard a lot about this author and I am keen on acquiring this particular work. If it is available, I would appreciate it if you could provide me with information regarding its price and whether it can be reserved.",LocalDate.now());
			userMessageRepository.save(message2);


			BuyOrder order1=new BuyOrder("ORDER N-1232311",175.0,LocalDate.now(),client1,OrderStatus.PENDING,false);
			buyOrderRepository.save(order1);
			BuyOrder order2=new BuyOrder("ORDER N-2232222",56.0,LocalDate.now(),client1,OrderStatus.DELIVERED,false);
			buyOrderRepository.save(order2);
			BuyOrder order3=new BuyOrder("ORDER N-3333333",89.0,LocalDate.now(),client1,OrderStatus.ON_THE_WAY,false);
			buyOrderRepository.save(order3);

		};
	}
}